const std = @import("std");
const builtin = @import("builtin");

const tools = @import("tools.zig");

const required_zig_version = "0.16.0";

const Manifest = struct {
    id: []const u8,
    name: []const u8,
    description: []const u8,
    version: []const u8,
    build: BuildConfig = .{},
};

const BuildConfig = struct {
    artifact: ?[]const u8 = null,
};

pub fn build(b: *std.Build) !void {
    verifyZigVersion();

    const allocator = b.allocator;
    const io = b.graph.io;
    const cwd = std.Io.Dir.cwd();

    const tools_step = b.step(
        "tools",
        "Build all tools",
    );
    const registry_step = b.step(
        "registry",
        "Generate registry.js",
    );

    const clean_step = b.step("clean", "Remove build artifacts");

    const clean_registry = b.addSystemCommand(&.{ "rm", "-f", "tools/registry.js" });
    clean_registry.setName("clean registry.js");
    clean_step.dependOn(&clean_registry.step);

    const clean_cache = b.addSystemCommand(&.{ "rm", "-rf", ".zig-cache" });
    clean_cache.setName("clean zig-cache");
    clean_step.dependOn(&clean_cache.step);

    inline for (tools.tools) |tool| {
        tool.add(b, tools_step);
        tool.clean(b, clean_step);
    }

    var tools_dir = try cwd.openDir(io, "tools", .{
        .iterate = true,
    });
    defer tools_dir.close(io);

    var registry: std.ArrayList(u8) = .empty;
    defer registry.deinit(allocator);

    try registry.appendSlice(allocator,
        \\// Generated by `zig build`. DO NOT EDIT.
        \\
        \\export const TOOLS = [
        \\
    );

    var iterator = tools_dir.iterate();
    while (try iterator.next(io)) |entry| {
        if (entry.kind != .directory)
            continue;

        const tool_id = entry.name;
        var tool_dir = try tools_dir.openDir(io, tool_id, .{});
        defer tool_dir.close(io);

        const manifest_data = tool_dir.readFileAlloc(
            io,
            "manifest.json",
            allocator,
            .limited(1024 * 1024),
        ) catch |err| {
            std.log.err(
                "tools/{s}: unable to read manifest.json: {s}",
                .{ tool_id, @errorName(err) },
            );
            return error.InvalidManifest;
        };
        defer allocator.free(manifest_data);

        var parsed = std.json.parseFromSlice(
            Manifest,
            allocator,
            manifest_data,
            .{},
        ) catch |err| {
            std.log.err(
                "tools/{s}: invalid manifest.json: {s}",
                .{ tool_id, @errorName(err) },
            );
            return error.InvalidManifest;
        };
        defer parsed.deinit();

        const manifest = parsed.value;
        if (!std.mem.eql(u8, tool_id, manifest.id)) {
            std.log.err(
                "tools/{s}: manifest id is \"{s}\"",
                .{ tool_id, manifest.id },
            );
            return error.ManifestIdMismatch;
        }

        if (manifest.build.artifact) |artifact| {
            if (artifact.len == 0) {
                std.log.err(
                    "tools/{s}: build.artifact cannot be empty",
                    .{tool_id},
                );
                return error.InvalidArtifact;
            }

            if (std.mem.startsWith(u8, artifact, "/")) {
                std.log.err(
                    "tools/{s}: build.artifact must be relative",
                    .{tool_id},
                );
                return error.InvalidArtifact;
            }

            if (std.mem.indexOf(u8, artifact, "..") != null) {
                std.log.err(
                    "tools/{s}: build.artifact may not contain '..'",
                    .{tool_id},
                );
                return error.InvalidArtifact;
            }
        }

        try appendRegistryEntry(
            allocator,
            &registry,
            manifest,
        );
    }

    try registry.appendSlice(allocator,
        \\];
        \\
    );

    const write_files = b.addWriteFiles();

    const registry_file = write_files.add(
        "registry.js",
        registry.items,
    );

    const install_registry = b.addInstallFile(
        registry_file,
        "../tools/registry.js",
    );

    registry_step.dependOn(&install_registry.step);

    b.default_step.dependOn(tools_step);
    b.default_step.dependOn(registry_step);

    const serve_exe = b.addExecutable(.{
        .name = "serve",
        .root_module = b.createModule(.{
            .root_source_file = b.path("serve.zig"),
            .target = b.graph.host,
            .optimize = .Debug,
        }),
    });

    const serve_run = b.addRunArtifact(serve_exe);

    const serve_step = b.step(
        "serve",
        "Build tools, generate registry, and serve the site",
    );

    serve_run.step.dependOn(b.getInstallStep());
    serve_step.dependOn(&serve_run.step);
}

fn verifyZigVersion() void {
    const actual = builtin.zig_version;

    if (actual.major != 0 or actual.minor != 16 or actual.patch != 0) {
        std.log.err(
            "requires Zig {s}, found {d}.{d}.{d}",
            .{
                required_zig_version,
                actual.major,
                actual.minor,
                actual.patch,
            },
        );

        @panic("unsupported Zig version");
    }
}

fn appendRegistryEntry(
    allocator: std.mem.Allocator,
    registry: *std.ArrayList(u8),
    manifest: Manifest,
) !void {
    const entry = try std.fmt.allocPrint(
        allocator,
        \\  {{
        \\    id: "{s}",
        \\    name: "{s}",
        \\    description: "{s}",
        \\    version: "{s}"
        \\  }},
    ,
        .{
            manifest.id,
            manifest.name,
            manifest.description,
            manifest.version,
        },
    );
    defer allocator.free(entry);

    try registry.appendSlice(allocator, entry);
}
